### ISSUE TITLE
Nice idea, but the Python-Script does not work

### ISSUE THREAD

**Issue by gro1729** [spillerrec/sanify-latex#1]
I get the following stack-trace with python 2.7 and with python 3.2

Traceback (most recent call last):
  File "./sanify_latex.py", line 98, in <module>
    main()
  File "./sanify_latex.py", line 91, in main
    Parser().parseBytesStream( sys.stdin.buffer )
  File "./sanify_latex.py", line 87, in parseBytesStream
    self.handleScope( line.decode(sys.stdout.encoding) );
  File "./sanify_latex.py", line 68, in handleScope
    self.handleScope( trimmed[len(name)+1:] )
  File "./sanify_latex.py", line 72, in handleScope
    self.handleScope( trimmed[1:] )
  File "./sanify_latex.py", line 72, in handleScope
    self.handleScope( trimmed[1:] )
  File "./sanify_latex.py", line 70, in handleScope
    self.context.pop()
IndexError: pop from empty list

**Comment by spillerrec** [comment]
If you now get a "Sanify-Warning" about scopes, please share the raw output of pdflatex if you can, so I can find out why it fails

**Comment by gro1729** [comment]
Hello,

find enclosed the log-file of my latex-call

Regards from Andreas

Am 03.11.2015 14:23, schrieb Sebastian Wahl:

**Comment by spillerrec** [comment]
I'm not seeing the log-file, maybe GitHub ignored the email attachment? You can try doing it on the website, or sending it directly on my email: spillerrec at gmail.com

**Comment by spillerrec** [comment]
Guess what, Gmail marked the mail as spam, so I didn't notice it until today...
It should be able to pretty print it now, though with several thousand lines of output it is still not optimal. The reason I wrote this script is that warnings gets drowned in unimportant filler, so people don't notice that they make them. If it was easy to tell each time you compiled if you did something wrong, I believe a lot of LaTeX warnings would be fixed. It might be of interest to have some way of ignoring output you know is unimportant, but I'm not going to look into that right now, maybe next week.
